name: Mutant

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mutant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - run: bundle exec rake mutant
